SudisIm/Controllers/AbsenceController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using NHibernate;
using SudisIm.DAL.NHibernate;
using SudisIm.DAL.Repositories;
using SudisIm.Model.Models;
using SudisIm.Model.Repositories;

namespace SudisIm.Controllers
{
    public class AbsenceController : Controller
    {
        private readonly IRefereeRepository refereeRepository;
        private readonly IAbsenceRepository absenceRepository;

        #region Constructors
        public AbsenceController()
            : this(NHibernateHelper.Instance.OpenSession())
        { }

        public AbsenceController(ISession session)
            : this(new RefereeRepository(session), new AbsenceRepository(session))
        { }

        public AbsenceController(IRefereeRepository refereeRepo, IAbsenceRepository absenceRepository)
        {
            this.refereeRepository = refereeRepo;
            this.absenceRepository = absenceRepository;
        }

        #endregion /Constructors
        [Authorize(Roles = "referee")]
        // GET: Absence
        public ActionResult Index()
        {
            var referee = this.refereeRepository.GetRefereeByUser(User.Identity.Name);

            return View(referee.Absences);
        }

        [Authorize(Roles = "referee")]
        // GET: Absence/Create
        public ActionResult Create()
        {
            var absence = new Absence()
            {
                StartDate = DateTime.Now,
                EndDate = DateTime.Now.AddDays(1)
            };
            return View(absence);
        }

        [Authorize(Roles = "referee")]
        // GET: Absence/Create

        [HttpPost]
        public ActionResult Create(Absence newAbsence)
        {
            // Assign referee
            var referee = this.refereeRepository.GetRefereeByUser(User.Identity.Name);
            newAbsence.Referee = referee;

            this.absenceRepository.AddAbsence(newAbsence);

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "referee")]
        public ActionResult Delete( int id)
        {
            // Check owner
            var referee = this.refereeRepository.GetRefereeByUser(User.Identity.Name);
            if(!referee.Absences.Any(a => a.Id == id))
                throw new Exception("Ne mozete izbrisati tudje odsustvo");

            this.absenceRepository.RemoveAbsence(id);
            return RedirectToAction("Index");
        }
    }
}

SudisIm/Controllers/CalendarController.cs
using System.Linq;
using System.Web.Mvc;
using NHibernate;
using SudisIm.DAL.NHibernate;
using SudisIm.DAL.Repositories;
using SudisIm.Model.Repositories;
using SudisIm.Models.Calendar;
using SudisIm.Services.Users;

namespace SudisIm.Controllers
{
    public class CalendarController : Controller
    {
        private readonly IGameRepository gameRepository;
        private readonly IRefereeRepository refereeRepository;
        #region Constructors
        public CalendarController()
            : this(NHibernateHelper.Instance.OpenSession())
        { }

        public CalendarController(ISession session)
            : this(new GameRepository(session), new RefereeRepository(session))
        { }

        public CalendarController(IGameRepository gameRepo, IRefereeRepository refereeRepo)
        {
            this.gameRepository = gameRepo;
            this.refereeRepository = refereeRepo;
        }

        #endregion /Constructors
        [Authorize(Roles = "referee")]
        // GET: Calendar
        public ActionResult Index()
        {
            var referee = this.refereeRepository.GetRefereeByUser(User.Identity.Name);
            var games = this.gameRepository.GetGamesForReferee(referee.Id);
            var calendarEvents = games.Select(g => (CalendarEventDto)g).ToList();
            var absenceEvents = referee.Absences.Select(a => (CalendarEventDto) a);
            calendarEvents.AddRange(absenceEvents);
            var calendarVM = new RefereeCalendarViewModel()
            {
                Events = calendarEvents

            };
            return View(calendarVM);
        }
    }
}

SudisIm/Controllers/GamesController.cs
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using NHibernate;
using SudisIm.DAL.NHibernate;
using SudisIm.DAL.Repositories;
using SudisIm.Model.Models;
using SudisIm.Model.Repositories;
using SudisIm.Models.Games;

namespace SudisIm.Controllers
{
    public class GamesController : Controller
    {
        private readonly IGameRepository gameRepository;
        private readonly ILicenceRepository licenceRepository;
        private readonly ITeamRepository teamRepository;
        private readonly IRefereeRepository refereeRepository;
        private readonly ICityRepository cityRepository;
        #region Constructors
        public GamesController()
            : this(NHibernateHelper.Instance.OpenSession())
        { }

        public GamesController(ISession session)
            : this(new GameRepository(session), new LicenceRepository(session), new TeamRepository(session), new RefereeRepository(session), new CityRepository(session) )
        { }

        public GamesController(IGameRepository gameRepo, ILicenceRepository licenceRepo, ITeamRepository teamRepo, IRefereeRepository refereeRepo, ICityRepository cityRepo)
        {
            this.gameRepository = gameRepo;
            this.licenceRepository = licenceRepo;
            this.teamRepository = teamRepo;
            this.refereeRepository = refereeRepo;
            this.cityRepository = cityRepo;
        }

        #endregion /Constructors
        [Authorize(Roles = "admin")]
        // GET: Games
        public ActionResult Index()
        {
            return View(this.gameRepository.GetGames());
        }

        public ActionResult Create()
        {
            return View(GetCreateViewModel());
        }


        private GameCreateViewModel GetCreateViewModel()
        {
            return new GameCreateViewModel()
            {
                Cities = this.cityRepository.GetCities(),
                Licences = this.licenceRepository.GetLicences(),
                Referees = this.refereeRepository.GetReferees().ToList(),
                Teams = this.teamRepository.GetTeams(),
                Game = new Game()
            };
        }

        [HttpPost]
        public ActionResult Create(GameCreateViewModel gameCreateViewModel)
        {
            return View();
        }
    }
}

SudisIm/Controllers/NotificationController.cs
using NHibernate;
using SudisIm.DAL.NHibernate;
using SudisIm.DAL.Repositories;
using SudisIm.Model.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SudisIm.Controllers
{
    public class NotificationController : Controller
    {
        private readonly INotificationRepository notificationsRepository;
        private readonly IRefereeRepository refereeRepository;

        #region Constructors
        public NotificationController()
            : this(NHibernateHelper.Instance.OpenSession())
        { }

        public NotificationController(ISession session)
            : this(new NotificationRepository(session), new RefereeRepository(session))
        { }

        public NotificationController(INotificationRepository notificationRepository, IRefereeRepository refereeRepository)
        {
            this.notificationsRepository = notificationRepository;
            this.refereeRepository = refereeRepository;
        }
        #endregion

        // GET: Notification
        public ActionResult Index()
        {
            var referee = this.refereeRepository.GetRefereeByUser(User.Identity.Name);
            return View(this.notificationsRepository.GetNotificationsForReferee(referee.Id));
        }
    }
}

SudisIm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sudis im</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sudiš im", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("admin"))
                    {
                        <li>@Html.ActionLink("Kalendar", "AdminIndex", "Calendar")</li>
                        <li>@Html.ActionLink("Utakmice", "Index", "Games")</li>
                        <li>@Html.ActionLink("Suci", "Index", "Referee")</li>
                    }
                   @if (User.IsInRole("referee"))
                   {
                       <li>@Html.ActionLink("Kalendar", "Index", "Calendar")</li>
                       <li>@Html.ActionLink("Odsutnost", "Index", "Absence")</li>
                       <li>@Html.ActionLink("Obavijesti","Index","Notification")</li>
                   }

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sudis im</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>